### ISSUE TITLE
Приглашаю всех принять в развитии проекта по изучению питона на русском языке

### ISSUE THREAD

**Issue by BEPb** [BEPb/Python-100-days#5]
Приглашаю всех принять в развитии проекта по изучению питона на русском языке. Вы можете оставлять свои предложения прямо здесь или писать мне на почту.

**Comment by NastyMel** [comment]
Здравствуйте, наткнулась на ваш курс, просто супер) но почему- то нет дней после  40

**Comment by BEPb** [comment]
Здравствуйте, этот проект я начинал для архивации своего успеха, но не был уверен, что это нужно еще хоть кому-нибудь.

**Comment by it255ru** [comment]
Привет! Хочу помочь проекту!

**Comment by nsvk13** [comment]
> Здравствуйте, этот проект я начинал для архивации своего успеха, но не был уверен, что это нужно еще хоть кому-нибудь.

Здравствуйте! Будет-ли продолжение? Очень хотелось бы посмотреть на последующие дни.

**Comment by BEPb** [comment]
Я сейчас работаю над другим проектом, и не уверен что следует развивать этот....
